#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle init"
#

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Use the maximum available or specified
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Resolve links
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="$(dirname "$PRG")/$link"
    fi
done

SAVED="$(pwd)"
cd "$(dirname "$PRG")" > /dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" > /dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# OS specific support
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
    CYGWIN* ) cygwin=true ;;
    Darwin* ) darwin=true ;;
    MSYS* | MINGW* ) msys=true ;;
    NONSTOP* ) nonstop=true ;;
esac

JAVA_EXE=java
if test -n "$JAVA_HOME" ; then
    JAVA_EXE="$JAVA_HOME/bin/java"
fi

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
